import { useState, useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import { useAuthStore } from "../store/authStore";
import { Menu, X } from "lucide-react";

export default function Navbar() {
  const token = useAuthStore((s) => s.token);
  const location = useLocation();
  const [open, setOpen] = useState(false);
  const [runtimeVersion, setRuntimeVersion] = useState<string | null>(null);

  useEffect(() => {
    // try to load runtime version file generated by bump script (served from public/)
    fetch('/version.json')
      .then((res) => {
        if (!res.ok) throw new Error('no version file');
        return res.json();
      })
      .then((json) => {
        if (json && json.version) setRuntimeVersion(String(json.version));
      })
      .catch(() => {
        /* ignore, fallback to build-time value */
      });
  }, []);

  const navItems = [
    { name: "Home", path: "/" },
    { name: "Start Order", path: "/order" },
    ...(token ? [{ name: "Admin", path: "/admin" }] : []),
  ];

  // productTypes previously used for quick links; removed because unused

  return (
    <nav className="sticky top-0 z-50 backdrop-blur-lg bg-gradient-to-r from-blue-700 via-indigo-700 to-blue-800 text-white shadow-md border-b border-white/10">
      <div className="container mx-auto flex justify-between items-center px-4 py-3">
        {/* Brand */}
        <div className="flex items-center gap-2">
          <Link
            to="/"
            className="text-2xl font-extrabold tracking-tight bg-gradient-to-r from-white to-blue-200 bg-clip-text text-transparent hover:opacity-90 transition-opacity"
          >
            <img src="/logo.png" alt="Logo" className="inline h-auto w-64 mr-2 -mt-1" />
          </Link>
          <span className="text-xs text-blue-200/70">v{runtimeVersion ?? import.meta.env.VITE_APP_VERSION ?? '1.0.0'}</span>
        </div>

        {/* Desktop links */}
        <div className="hidden md:flex space-x-4 items-center">
          {navItems.map((item) => {
            const isActive = location.pathname === item.path;
            return (
              <Link
                key={item.path}
                to={item.path}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-all duration-300 ${isActive
                  ? "bg-white text-blue-700 shadow-sm"
                  : "bg-white/10 hover:bg-white/20  text-white"
                  }`}
              >
                {item.name}
              </Link>
            );
          })}

          {/* Product type quick links
          <div className="flex items-center space-x-2 ml-4">
            {productTypes.map((p) => (
              <Link key={p.path} to={p.path} className="px-3 py-1 text-sm rounded-md bg-white/10 hover:bg-white/20">
                {p.name}
              </Link>
            ))}
          </div> */}
        </div>

        {/* Mobile menu button */}
        <button
          className="md:hidden p-2 rounded-lg hover:bg-white/10 transition"
          onClick={() => setOpen(!open)}
        >
          {open ? <X size={24} /> : <Menu size={24} />}
        </button>
      </div>

      {/* Mobile dropdown */}
      {open && (
        <div className="md:hidden bg-blue-800/95 backdrop-blur-xl border-t border-white/10">
          <div className="flex flex-col items-center space-y-3 py-4 ">
            {navItems.map((item) => {
              const isActive = location.pathname === item.path;
              return (
                <Link
                  key={item.path}
                  to={item.path}
                  onClick={() => setOpen(false)}
                  className={`w-3/4 text-center px-4 py-2 rounded-full text-sm font-medium transition ${isActive
                    ? "bg-white text-blue-700 shadow-sm"
                    : "bg-white/10 hover:bg-white/20 text-white"
                    }`}
                >
                  {item.name}
                </Link>
              );
            })}
          </div>
        </div>
      )}
    </nav>
  );
}
